// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kroefwbuhxreqklfttot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyb2Vmd2J1aHhyZXFrbGZ0dG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzMzQ0NDIsImV4cCI6MjA5MDkxMDQ0Mn0.Fr2n3XnWLq2EbfU_XOMk8PxrWhDvjf5qo6dGt8ZjyYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});